### ISSUE TITLE
Help wanted?

### ISSUE THREAD

**Issue by j-maas** [Leonqn/rutebot#1]
This is such a nicely architectured framework! I was looking for one that provided exactly this level of flexibility. Really well done!

I was wondering whether you would like some input on the code from my part. There are a few small things I noticed while browsing through the code. I could open PRs for them, if you'd like. For example:

- [`update_poll_stream.rs`](https://github.com/Leonqn/rutebot/blob/master/src/updates_poll_stream.rs) contains an `UpdatesPoolStream` struct. Maybe it should be renamed accordingly?
- The [`send_text.rs`](https://github.com/Leonqn/rutebot/blob/master/src/requests/send_text.rs#L45) module corresponds to the [`sendMessage` Telegram API method](https://core.telegram.org/bots/api#sendmessage). Maybe also rename?
- The doc comment seem to be [flipped](https://github.com/Leonqn/rutebot/blob/master/src/requests.rs#L27) for some of the request modules.

I would be happy to start contributing some small PRs for these things, so I can get to know the code base. Maybe I'll even find time to propose some bigger contributions, but for now, would you like me to work on issues like the above?

**Comment by Leonqn** [comment]
Hello! Help is always wanted :)
I agree with with changes and it would be great if you open PR

**Comment by j-maas** [comment]
Very cool. I'll just open a bunch of small PRs for any individual change. That way you can pick and choose which ones you like. ;)

**Comment by j-maas** [comment]
I hope I didn't drown you in PRs and issues. 🙈 I will chill out now for a while, get some sleep, etc.

**Comment by Leonqn** [comment]
No you didn't. 
Great job!
