### ISSUE TITLE
Support for getHistory

### ISSUE THREAD

**Issue by 0xpr03** [Leonqn/rutebot#21]
Hi, I can't find [getHistory](https://core.telegram.org/method/messages.getHistory) and anything related to history in rutebot. Am I missing something or is there a planned support for this ?
I'd also like to help with that, but don't know where to start.

**Comment by Leonqn** [comment]
Hello! Currently rutebot supports only [bot api](https://core.telegram.org/api#bot-api) and i have no plans for supporting telegram client api methods such as getHistory.

**Comment by 0xpr03** [comment]
Oh shoot I'm sorry, seems like I mistook the api and thought it's part of one.
