### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by j-maas** [Leonqn/rutebot#6]
Running `cargo fmt` makes changes to 52 files. I think it's worth setting up auto-formatting with [rustfmt](https://github.com/rust-lang/rustfmt#on-the-stable-toolchain).

You could even let the CI check that everything is properly formatted with `cargo fmt -- --check`, therefore ensuring that only properly formatted code is merged.

I did not yet make a PR, because changing formatting on 52 files might be annoying if you are currently working on them. I suggest you simply run the command yourself when it best suits you.

**Comment by Leonqn** [comment]
Thanks!
I'll run fmt after merging your PR about `send_text`

**Comment by Leonqn** [comment]
Done
