### ISSUE TITLE
Reexport requests submodules

### ISSUE THREAD

**Issue by j-maas** [Leonqn/rutebot#7]
There are a lot of modules in `requests/`. If I understand correctly, these are just to avoid having one gigantic file. But importing them seems slightly tedious.

We could reexport the request types from `requests` itself. There shouldn't be any nameclashes, because the names are the ones from the Telegram API, which doesn't have nameclashes. And it would simplify importing the request types.

The only change needed is to convert each [line](https://github.com/Leonqn/rutebot/blob/master/src/requests.rs#L22) from
```rust
pub mod send_text;
```
to
```rust
mod send_text;
pub use send_text::*;
```

Do you want me to work on a PR for this?

**Comment by Leonqn** [comment]
Yes you understand it correctly. 
It would be nice if you do it.
